title: Vagrant UTM
description: >-
  vagrant_utm is a Vagrant plugin which adds UTM provider to Vagrant, 
  allowing Vagrant to control and provision machines via UTM's API
baseurl: "/vagrant_utm" # the subpath of your site, e.g. /blog
url: "https://naveenrajm7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: naveenrajm7/vagrant_utm # for github-metadata  
github_username:  naveenrajm7


# Build settings
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-remote-theme

# Website settings

logo: "/assets/images/logo.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/logo.png"

heading_anchors: true

nav_external_links:
  - title: Vagrant
    url: https://www.vagrantup.com
  - title: UTM for macOS
    url: https://mac.getutm.app
  - title: Packer plugin for UTM
    url: https://github.com/naveenrajm7/packer-plugin-utm
  - title: UTM Gallery
    url: https://naveenrajm7.github.io/utm-gallery/


# Aux links for the upper right navigation
aux_links:
  "Vagrant UTM on GitHub":
    - "//github.com/naveenrajm7/vagrant_utm"

# Edit on Github
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/naveenrajm7/vagrant_utm"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"


# callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# For copy button on code
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: "Copyright &copy; 2024 Naveenraj Muthuraj. Distributed by an <a href=\"https://github.com/naveenrajm7/vagrant_utm/tree/main/LICENSE.txt\">MIT license.</a>"
